# Generated by Django 4.0.5 on 2022-06-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='priority_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='status_id',
        ),
    ]
