# Generated by Django 4.0.5 on 2022-06-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.status'),
        ),
    ]
