# Generated by Django 4.0.5 on 2022-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
