# Generated by Django 4.0.5 on 2022-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
