# Generated by Django 4.0.5 on 2022-06-21 03:33

from django.db import migrations, models
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspace_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=workspace.models.nameFile),
        ),
    ]
