# Generated by Django 4.0.5 on 2022-06-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
