# Generated by Django 4.0.5 on 2022-06-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='account.theme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
