# Generated by Django 4.0.5 on 2022-06-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_auth_id_alter_profile_theme_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Themes',
        ),
    ]
